baseurl = "http://www.briansantero.com/"
languageCode = "en-us"
title = "Brian Santero"
buildDrafts = true
DisableRSS = true
DisableSitemap = true
canonifyurls = false
[[menu.main]]
  name = "About"
  weight = -110
  identifier = "About"
  url ="/"
[[menu.main]]
  name = "Blahg"
  weight = -100
  identifier = "blahg"
  url ="/blahg"
[[menu.main]]
  name = "Duckchase"
  weight = -90
  identifier = "Duckchase"
  url ="/duckchase/"
[[menu.main]]
  name = "Projects"
  weight = -80
  identifier = "Projects"
  url ="/project/"
[[menu.main]]
  name = "Contact"
  weight = -60
  identifier = "Contact"
  url ="/contact/"
